@Api_HostAddress = https://localhost:7243


#Call endpoint 1 (get)
Get {{Api_HostAddress}}/employee/2

###

#Call endpoint 2 (post)
Post {{Api_HostAddress}}/employee
Content-Type: application/json
{
  "id": 0,
  "firstName": "Nimal",
  "lastName": "Perera"
}

###

#Call endpoint 3 (get)
Get {{Api_HostAddress}}/person/5

###

#Call endpoint 4 (post)
Post {{Api_HostAddress}}/person
Content-Type: application/json
{
  "id": 0,
  "firstName": "Ushan",
  "lastName": "Perera"
}

###
